version: '2.1'
services:
  mysql:
    image: mysql:5.7.36
    #image: mysql/mysql-server:8.0.23
    container_name: mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: quizz
      MYSQL_USER: php_user
      MYSQL_PASSWORD: secret321
    ports:
    - '3306:3306'
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
    - '8080:80'
    - '8443:443'
